### ISSUE TITLE
Dokumentation Fehlen 

### ISSUE THREAD

**Issue by Berkedmy** [Sergen-B/Wissenschaftliches_Arbeiten_2023-24#5]
Hallo an das Team, 

Die Dokumentationen fehlen wollte hier nochmal kurz bescheid geben.

Mit freundlichen Grüßen
Berke

**Comment by Sergen-B** [comment]
Danke für die Erinnerung, die Dokumentation zu Aufgabe 2a) (v) habe ich hinzugefügt.

Mit freundlichen Grüßen,
Sergen

**Comment by Ahmgh123** [comment]
Alles klar vielen danke für die Erinnerung . Ich habe sie zu Aufgabe 2a)(ii) auch hinzugefügt .

Mit freundlichen grüßen .
Ahmed Ghroubi

**Comment by Eyaghroubi** [comment]
Hallo zusammen,
ich habe jetzt auch die Kommentare für meinen Teil der Aufgabe 2(iv) hinzugefügt. Danke für die Erinnerung.

Mit freundlichen Grüßen,
Eya Ghroubi

**Comment by SeAd2912** [comment]
Hallo zusammen, 
ich habe jetzt ebenfalls meine Dokumentation zu Aufgabe 2 (iii) hinzugefügt.

Mit freundlichen Grüßen,
Seymen
