### ISSUE TITLE
Aufgabe 4

### ISSUE THREAD

**Issue by SeAd2912** [Sergen-B/Wissenschaftliches_Arbeiten_2023-24#7]
Hallo,

Sergen und Berke seid ihr fertig mit der Aufgabe 4 ?

Mit freundlichen Grüßen,

Seymen

**Comment by Sergen-B** [comment]
Hallo,
ich bin mit meinem Teil eigentlich fertig.

Mit freundlichen Grüßen,
Sergen

**Comment by Berkedmy** [comment]
Hey,  
bin auch fertig mit meiner Aufgabe. 

Mit freundlichen Grüßen 
Berke
