### ISSUE TITLE
Aufgabe 5 - Ergänzungen:

### ISSUE THREAD

**Issue by Sergen-B** [Sergen-B/Wissenschaftliches_Arbeiten_2023-24#8]
Hallo nochmal,

wir drei wären jetzt erstmal fertig mit Aufgabe 4 und unseren Analysen. Habt ihr vielleicht noch andere Sachen, die ihr ergänzen könnt oder wo ihr einen Fehler bei unserer Analyse seht?

Mit freundlichen Grüßen,
Sergen

**Comment by Eyaghroubi** [comment]
Hallo zusammen,

ich wollte einige Gedanken zu unseren aktuellen Analysen teilen. Zuerst zur Korrelation zwischen dem Ticketpreis (Fare) und dem Geschlecht (Sex) – es scheint, dass diese fast null ist. Das finde ich ziemlich interessant und auch logisch, wenn man bedenkt, dass viele Passagiere auf der Titanic Teil von Familien oder Paaren waren. Es könnte darauf hindeuten, dass Ticketpreise unabhängig vom Geschlecht festgelegt wurden, was ein spannender Einblick in die damaligen gesellschaftlichen Normen ist.

Bezüglich der Korrelation zwischen Alter (Age) und Überleben (Survived) – diese liegt bei -0.07881578. Obwohl es eine negative Korrelation ist, was darauf hindeutet, dass ältere Passagiere geringere Überlebenschancen hatten, ist der Wert relativ niedrig. Das bedeutet, dass Alter und Überleben nicht stark miteinander verbunden sind. Es ist faszinierend zu sehen, dass trotz der allgemeinen Annahme, dass ältere Menschen vielleicht weniger Chancen hatten zu überleben, die Daten dies nicht stark unterstützen. Vielleicht gibt es andere Faktoren, die eine größere Rolle gespielt haben, wie z.B. die Position der Kabine oder der Zugang zu Rettungsbooten.
Mit freundlichen Grüßen,
Sergen

**Comment by Eyaghroubi** [comment]
Hallo nochmal ,

Mir kam noch eine Idee: Wie wäre es, wenn wir untersuchen, ob es einen Unterschied in den Überlebenschancen zwischen den Passagieren auf verschiedenen Decks oder zwischen Steuerbord und Backbord gab? Könnte spannend sein zu sehen, ob die Position auf dem Schiff irgendwie die Überlebenschancen beeinflusst hat. Was haltet ihr davon?

**Comment by Sergen-B** [comment]
Hallo,

die Idee den Überlebensstatus mit den Deckpositionen oder der Kabinenseite zu vergleichen finde ich gut und auch nachvollziehbar. Vielleicht könnte das hier einer analysieren und dann seine Ergebnisse im Skript hinzufügen?

Den Zusatz für den Vergleich zwischen Ticketpreisen und Geschlechtern halte ich ebenfalls für sehr konstruktiv. Ich werde das zu meinen Ergebnissen definitiv ergänzen, da ich den Familienaspekt nicht bedacht hatte.

Mit freundlichen Grüßen,
Sergen

**Comment by Ahmgh123** [comment]
Hallo Team,

ich habe darüber nachgedacht, wie wir weiter in die Titanic-Daten eintauchen können, und mir fiel ein interessanter Aspekt auf, den wir vielleicht noch genauer untersuchen können : der Zusammenhang zwischen dem Ticketpreis (Fare) und den Überlebenschancen (Survived). Es gibt die weit verbreitete Annahme, dass Passagiere mit höheren Ticketpreisen, also wahrscheinlich reichere Passagiere, bessere Chancen hatten, das Unglück zu überleben. Diese Annahme könnte auf der Vorstellung beruhen, dass diese Passagiere bevorzugten Zugang zu Rettungsbooten hatten oder sich in besser zugänglichen Kabinen befanden.

Eine Analyse dieser Beziehung könnte uns wertvolle Einblicke darüber geben, wie soziale Klassen und wirtschaftlicher Status in einer Notsituation eine Rolle spielten. Es wäre faszinierend zu sehen, ob unsere Daten diese Annahme stützen oder ob wir vielleicht zu anderen Schlussfolgerungen kommen.

Was haltet ihr davon, diese Analyse durchzuführen? Gibt es bestimmte Methoden oder Ansätze, die ihr für geeignet haltet, um diese Hypothese zu untersuchen? Ich freue mich darauf, eure Meinungen und Vorschläge zu hören!

**Comment by Sergen-B** [comment]
Nochmals hallo an alle,

die Analyseidee finde ich ebenfalls sehr gut, um die von dir vorgelegte These anhand unseres Datensatzes zu untersuchen. Wir haben mit der Funktion punkt_biseriale_korrelation_und_stats() auch eine gute und effiziente Möglichkeit, um dieser Korrelation auf den Grund zu gehen. Ich könnte versuchen, dies zu analysieren, die Ergebnisse würde ich dann in die Datei beifügen.

**Comment by Ahmgh123** [comment]
Hi @Sergen-B
 Ich freue mich darauf, deine Ergebnisse in der Datei zu sehen .

**Comment by Berkedmy** [comment]
Hallo Eya,

Ich habe die Analyse bezüglich der Korrelation zwischen Alter (Age) und Überleben (Survived) überdacht und auch geändert du hast recht. 

Mit freundlichen Grüßen 
Berke

**Comment by Eyaghroubi** [comment]
Hallo Berke,

danke fürs Anpassen der Analyse! Bin gespannt, was wir jetzt daraus lernen können.

Viele Grüße,
Eya

**Comment by Eyaghroubi** [comment]
Hey Team,

Ahmed und ich haben gerade die Analyse über den Zusammenhang zwischen den Überlebenschancen und der Schiffsseite (Backbord vs. Steuerbord) abgeschlossen. Wir haben die Ergebnisse in Aufgabe 5 direkt nach Aufgabe 4 eingetragen. Ganz entgegen unserer Erwartungen zeigen die Ergebnisse, dass es zwar einen erkennbaren prozentualen Unterschied in den Überlebensraten zwischen den beiden Schiffsseiten gibt, unsere statistischen Tests jedoch darauf hindeuten, dass die Schiffsseite keinen starken Einfluss auf die Überlebenschancen hatte.

**Comment by Sergen-B** [comment]
Hallo an alle aus dem Team,

ich habe nun ebenfalls meine Analyse zum Verhältnis zwischen Ticketpreis und Überleben der Passagiere hinzugefügt, die Ahmed vorgeschlagen hatte. Tatsächlich ist These, dass Reiche bevorzugt werden, anhand dieser Daten nicht abwegig, da eine positive Korrelation ermittelt werden kann, die auch nicht wirklich klein ist. Das lässt dann vermuten, dass es auch Bevorzugung von Reicheren auf der Titanic gab, was ein eher düsterer Einblick in die Sichtweisen der zuständigen Rettungskräfte wäre.

**Comment by Sergen-B** [comment]
Gibt es noch weitere Ergänzungen oder ähnliches oder darf ich diesen Issue schließen?

Mit freundlichen Grüßen,
Sergen

**Comment by Berkedmy** [comment]
Kannst es von mir aus schließen

**Comment by SeAd2912** [comment]
Ich hätte keine weiteren Ergänzungen. Von mir aus kannst du es schließen

**Comment by Eyaghroubi** [comment]
bei mir auch :)

**Comment by Ahmgh123** [comment]
Bei mir auch !
