### ISSUE TITLE
Fragen oder noch Anmerkungen 

### ISSUE THREAD

**Issue by Eyaghroubi** [Sergen-B/Wissenschaftliches_Arbeiten_2023-24#9]
Hello zusammen ,

habt ihr noch Fragen oder Anmerkungen bzw sind wir fertig mit dem Projekt ?

**Comment by Sergen-B** [comment]
Hallo,

ich würde sagen, dass wir fertig sind. Ich habe zumindest nichts mehr hinzuzufügen.

**Comment by ahmed-ghroubi** [comment]
Hallo , 

Ich habe selber nichts hinzuzufügen .

**Comment by SeAd2912** [comment]
Ich wuerde mich euch anschließen und sagen, das wir auch fertig sind.

**Comment by Berkedmy** [comment]
Hey, 

Ich habe auch nichts Hinzuzufügen :)
